# Generated by Django 2.2.13 on 2020-06-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200629_0554"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="hgfhfh",),
        migrations.RemoveField(model_name="customtext", name="jhygjg",),
    ]
