# Generated by Django 2.2.13 on 2020-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200629_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='fgwsregagqg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
