# Generated by Django 2.2.13 on 2020-06-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customtext_fgwsregagqg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
    ]
